/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:4ebcd379-60ef-4d5b-90a4-bce71444513a",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_C4m0bZP7D",
    "aws_user_pools_web_client_id": "7bo0oc447vg668rr359bsd71ss",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ln47mvwh3rhave4p4ekyeu5pe4.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "apif8da427c",
            "endpoint": "https://0u1224nf5k.execute-api.ap-northeast-1.amazonaws.com/prod",
            "region": "ap-northeast-1"
        }
    ]
};


export default awsmobile;
