/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:51da04b0-a2fb-4cc5-b292-d502c63e55cd",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_QMnssRr5O",
    "aws_user_pools_web_client_id": "1br6sguhmg6kk4j7ojgdd2frhc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://k5nzwcst4jcjxer3uewsienv4u.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
